### ISSUE TITLE
[Issue] Engineer's Decor "small tree cutter" only chops the bottom log of the Rubberwood tree

### ISSUE THREAD

**Issue by shrad1994** [Jake-E/Myrtrees#16]
### Minecraft Version

1.19.2

### Modloader

43.1.47

### Mod version

1.2.0-build.31

### Repeatable?

- [x] Yes

### Link to log files

There are no log files that would be helpful to my knowledge.

### Steps to reproduce the issue

1. Place small tree cutter
2. Place sapling from Rubberwood Tree in front of it, apply bonemeal if wanted for rapid growth
3. wait until the small tree cutter finishes chopping
4. observe only bottom block being broken when the typical behavior of said block is to chop the entire tree down.

### Description of the issue you are having

https://github.com/AllTheMods/ATM-8/issues/485

Here is a greater explanation as to my problem. I've also reported this to both ATM8 (linked above) as well as to engineer's decor. 

I'm not really sure which mod is sourcing the problem but every other tree I've tried so far seems to work just fine.

### Information

- [X] I have provided as much information as possible

**Comment by stfwi** [comment]
Hey Jake, I'd like to quickly cross-ref the issue in ED, I tend to fix it in the Cutter. Could you risk a glance and tell if you're with me there? Cheers, wile
https://github.com/stfwi/engineers-decor/issues/228#issuecomment-1362539232

**Comment by Jake-E** [comment]
Hey @stfwi. The issue does stem from the 2nd block in the tree being a different block. If you need me to add a tag to both blocks I'll happily do that :) Sorry for the unintentional issue!

**Comment by stfwi** [comment]
Hi again, oky I made an implementation in the cutter config (that allows the two mods being both optionally installed in a pack without getting undefined-tag-problems), and shrad has already tested it in his ATM setup, looks good. So we can also close the issue here.

An idea crossed my mind while coding... if other chopping machines get the same problem: If the filled rubber does not need a block entity (I didn't check the code there), a blockstate flag `filled` could allow you to control the optics and drops of a log, but you would always have the same log block that can be detected by the choppers. In the current MC version such a change would break existing worlds, but for future MC versions it may be worth an option in case you do changes in the code.
Godspeed; Cheer's,-
