### ISSUE TITLE
[Feature Request] 1.19.2 tag for CurseForge

### ISSUE THREAD

**Issue by OffBy0x01** [Jake-E/Myrtrees#22]
### Feature Description

KubeJS, Create, and several other major mods are only available on 1.19.2, not 1.19.

If you have time could you please bump the release version to 1.19.2, I'd really like to include this.

**Comment by corgiblu** [comment]
I just tried and it seems to work fine on 1.19.2!

**Comment by ColonelGerdauf** [comment]
the mod specificity is the problem here. The listing on Forge is simply listed as "1.19". This will make it difficult with, for instance, launchers getting the tag data to do an update when the instance is 1.19.2.

CurseForge allows for a range of compatible subversions, and due to the peculiar nature of the 1.19 update cycle, it is "1.19-1.19.2"
